### ISSUE TITLE
TypeError: code.replace is not a function while parsing file

### ISSUE THREAD

**Issue by tacomanator** [quarterto/Anyify#4]
Was previously using liveify and saw that you deprecated it in favor of Anyify. I tried to replace liveify, using the following command for compilation:

```browserify -t [ anyify --ls [ livescript?compile ] ] index.ls -o index.js```

but get an error:

```
TypeError: code.replace is not a function while parsing file: /Users/drew/Code/ls-test/index.ls
    at Object.exports.tokenize (/Users/drew/Code/ls-test/node_modules/livescript/lib/lexer.js:22:30)
    at Object.exports.lex (/Users/drew/Code/ls-test/node_modules/livescript/lib/lexer.js:4:26)
    at exports.compile (/Users/drew/Code/ls-test/node_modules/livescript/lib/index.js:45:32)
    at Unstream.transformFn (/Users/drew/Code/ls-test/node_modules/anyify/lib/index.js:55:20)
    at Unstream._flush (/Users/drew/Code/ls-test/node_modules/anyify/node_modules/unstream/unstream.js:63:8)
    at Unstream.<anonymous> (_stream_transform.js:118:12)
    at Unstream.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Unstream.emit (events.js:166:7)
    at prefinish (_stream_writable.js:458:12)
```

I'm using livescript 1.4.0 and browserify 11.2.0.

I put together a very simple test repository here: https://github.com/tacomanator/anyify-test.

Just run `npm run build` and you should see the error.

**Comment by quarterto** [comment]
This is almost certainly fixed by  #3.
